apiVersion: v1
kind: Service
metadata:
  name: microservice-service
spec:
  selector:
    app: micro-service
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 8000
    name: broker
    targetPort: 3000
