version: '3'

services:
  broker:
    build: ./broker
    ports:
      - "3000:3000"
  service1:
    build: ./service1
    ports:
      - "3001:3001"
  service2:
    build: ./service2
    ports:
      - "3002:3002"
  service3:
    build: ./service3
    ports:
      - "3003:3003"