apiVersion: v1
kind: Service
metadata:
  name: microservice-service1
spec:
  selector:
    app: micro-service
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 8000
    name: service1
    targetPort: 3001
