apiVersion: v1
kind: Service
metadata:
  name: microservice-service3
spec:
  selector:
    app: micro-service
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 8000
    name: service3
    targetPort: 3003
