apiVersion: v1
kind: Service
metadata:
  name: microservice-service2
spec:
  selector:
    app: micro-service
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 8000
    name: service2
    targetPort: 3002
